name: Check and Test Python Project

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1 # 0 if you want to push to repo

      - name: Python set up
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # for Uberspace
          cache: "pip"

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # pip install -r requirements-dev.txt

      - name: Install and run pytest
        run: |
          scripts/copy_test_data.sh
          cp .streamlit/secrets-EXAMPLE.toml .streamlit/secrets.toml
          pip install pytest
          pytest
