# see https://docs.streamlit.io/develop/api-reference/configuration/config.toml

[global]

[logger]
level = "info"
messageFormat = "%(asctime)s\t%(levelname)s\t%(name)s\t%(message)s"

[client]
showErrorDetails = true

[runner]

[server]
port = 8501
maxUploadSize = 1 # MB
# restrict access to dev localhost
# this is modified by upload.sh
address = "127.0.0.1"
# this is modified by upload.sh
fileWatcherType = "watchdog"
# baseUrlPath = "/strava-streamlit"

[browser]
gatherUsageStats = false

[mapbox]

[theme]

[secrets]
